# Generated by Django 2.2 on 2020-12-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
