# Generated by Django 2.2 on 2020-12-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(choices=[('DEV', 'Software Developers'), ('DES', 'Graphic Designers'), ('ASO', ' Business Associative')], default='DEV', max_length=50),
        ),
    ]
