# Generated by Django 2.2 on 2020-12-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20201228_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
