# Generated by Django 2.2 on 2020-12-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
