# Generated by Django 2.2 on 2020-12-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20201230_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teamlead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
    ]
