# Generated by Django 2.2 on 2021-01-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_auto_20210105_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
